language: python
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install bitcoind python-qt4

install:
    - sudo python setup.py install

script:
    - python -m unittest discover
